// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            int32
	Username      pgtype.Text
	ChatID        pgtype.Int8
	LastMessageID pgtype.Int8
	Login         pgtype.Text
	Password      pgtype.Text
}
