// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users(username, chat_id, login, password)
VALUES($1, $2, $3, $4)
`

type CreateUserParams struct {
	Username pgtype.Text
	ChatID   pgtype.Int8
	Login    pgtype.Text
	Password pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.ChatID,
		arg.Login,
		arg.Password,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, chat_id, login, password FROM users
WHERE chat_id=$1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, chatID pgtype.Int8) (User, error) {
	row := q.db.QueryRow(ctx, getUser, chatID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ChatID,
		&i.Login,
		&i.Password,
	)
	return i, err
}
