// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users(username, chat_id, last_message_id, login, password)
VALUES($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	Username      pgtype.Text
	ChatID        pgtype.Int8
	LastMessageID pgtype.Int8
	Login         pgtype.Text
	Password      pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.ChatID,
		arg.LastMessageID,
		arg.Login,
		arg.Password,
	)
	return err
}
